-- liquibase formatted sql

-- changeset Dmitry:1

create table "bank_account"
(
    id                               bigint generated by default as identity PRIMARY KEY,
    wallet_id                        uuid not null,
    client_name                      text not null,
    account_balance                  float not null

);

-- changeset Dmitry:2

insert into bank_account (id, wallet_id, client_name, account_balance) values (1, '1ad33264-449d-4ecc-b217-83b525599552', 'Dmitry', 2000 );
